app_name = "healthcare"
app_title = "Healthcare"
app_publisher = "healthcare"
app_description = "healthcare"
app_icon = "octicon octicon-file-directory"
app_color = "grey"
app_email = "contact@frappe.io"
app_license = "MIT"

[required_apps]
"saxenabhishek/erpnext" = "aks-docs-info_toml"